baseurl = "https://kupferstich.github.io/"
languageCode = "de-de"
title = "Kupferstichsammlung Hamburg"

theme = "robust"

canonifyurls = true
paginate = 10

[taxonomies]
    # Optional. Use if you want tags and lists.
    erstellt = "erstellt"
    category = "categories"
    tags = "tags"

[params]
rss = true